package cmd

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/spf13/cobra"
)

var (
	backupOutput string
	backupTables string
)

var dbCmd = &cobra.Command{
	Use:   "db",
	Short: "Database operations",
}

var backupCmd = &cobra.Command{
	Use:   "backup",
	Short: "Dump database as INSERT statements",
	RunE: func(cmd *cobra.Command, args []string) error {
		pool, err := connectDB()
		if err != nil {
			return err
		}
		defer pool.Close()
		return runBackup(pool)
	},
}

var restoreCmd = &cobra.Command{
	Use:   "restore",
	Short: "Execute SQL file against database",
	RunE: func(cmd *cobra.Command, args []string) error {
		restoreInput, _ := cmd.Flags().GetString("input")
		if restoreInput == "" {
			return fmt.Errorf("--input flag required")
		}
		pool, err := connectDB()
		if err != nil {
			return err
		}
		defer pool.Close()
		return runRestore(pool, restoreInput)
	},
}

func init() {
	backupCmd.Flags().StringVar(&backupOutput, "output", "", "Output file (default: stdout)")
	backupCmd.Flags().StringVar(&backupTables, "tables", "", "Comma-separated table names (default: all)")

	restoreCmd.Flags().String("input", "", "SQL file to restore")

	dbCmd.AddCommand(backupCmd)
	dbCmd.AddCommand(restoreCmd)
	rootCmd.AddCommand(dbCmd)
}

var systemTables = map[string]bool{
	"schema_migrations":   true,
	"_drizzle_migrations": true,
}

func runBackup(pool *pgxpool.Pool) error {
	ctx := context.Background()

	var tables []string
	if backupTables != "" {
		for _, t := range strings.Split(backupTables, ",") {
			tables = append(tables, strings.TrimSpace(t))
		}
	} else {
		rows, err := pool.Query(ctx, `
			SELECT table_name FROM information_schema.tables
			WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
			ORDER BY table_name
		`)
		if err != nil {
			return fmt.Errorf("failed to list tables: %w", err)
		}
		for rows.Next() {
			var name string
			if err := rows.Scan(&name); err != nil {
				return err
			}
			if !systemTables[name] {
				tables = append(tables, name)
			}
		}
		rows.Close()
	}

	var out *os.File
	if backupOutput != "" {
		f, err := os.Create(backupOutput)
		if err != nil {
			return fmt.Errorf("failed to create file: %w", err)
		}
		defer f.Close()
		out = f
		fmt.Fprintf(os.Stderr, "Backing up to %s\n", backupOutput)
	} else {
		out = os.Stdout
	}

	fmt.Fprintln(out, "-- Courier SuperApp Database Backup")
	fmt.Fprintln(out, "-- Generated by courier-cli")
	fmt.Fprintln(out)

	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	for _, table := range tables {
		fmt.Fprintf(os.Stderr, "Backing up table: %s\n", table)

		colRows, err := tx.Query(ctx, `
			SELECT column_name FROM information_schema.columns
			WHERE table_schema = 'public' AND table_name = $1
			ORDER BY ordinal_position
		`, table)
		if err != nil {
			return fmt.Errorf("failed to get columns for %s: %w", table, err)
		}

		var columns []string
		for colRows.Next() {
			var col string
			if err := colRows.Scan(&col); err != nil {
				return err
			}
			columns = append(columns, col)
		}
		colRows.Close()

		if len(columns) == 0 {
			fmt.Fprintf(os.Stderr, "  Skipping %s (no columns found)\n", table)
			continue
		}

		fmt.Fprintf(out, "INSERT INTO %s (%s) VALUES\n", table, strings.Join(columns, ", "))

		dataRows, err := tx.Query(ctx, fmt.Sprintf("SELECT %s FROM %q", strings.Join(columns, ", "), table))
		if err != nil {
			return fmt.Errorf("failed to query %s: %w", table, err)
		}

		count := 0
		for dataRows.Next() {
			values := make([]interface{}, len(columns))
			valuePtrs := make([]interface{}, len(columns))
			for i := range values {
				valuePtrs[i] = &values[i]
			}
			if err := dataRows.Scan(valuePtrs...); err != nil {
				return fmt.Errorf("failed to scan row in %s: %w", table, err)
			}

			var vals []string
			for _, v := range values {
				vals = append(vals, formatValue(v))
			}

			if count > 0 {
				fmt.Fprint(out, ",\n")
			}
			fmt.Fprintf(out, "(%s)", strings.Join(vals, ", "))
			count++
		}
		dataRows.Close()

		if count == 0 {
			fmt.Fprint(out, "()")
		}
		fmt.Fprintln(out, ";\n")
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("failed to commit: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Backup complete. %d tables exported.\n", len(tables))
	return nil
}

func runRestore(pool *pgxpool.Pool, filePath string) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}

	ctx := context.Background()

	content := string(data)
	statements := splitSQL(content)

	total := 0
	for _, stmt := range statements {
		stmt = strings.TrimSpace(stmt)
		if stmt == "" || strings.HasPrefix(stmt, "--") {
			continue
		}
		fmt.Fprintf(os.Stderr, "Executing: %s\n", truncate(stmt, 80))
		_, err := pool.Exec(ctx, stmt)
		if err != nil {
			return fmt.Errorf("failed to execute statement: %w\nStatement: %s", err, truncate(stmt, 200))
		}
		total++
	}

	fmt.Fprintf(os.Stderr, "Restore complete. %d statements executed.\n", total)
	return nil
}

func splitSQL(content string) []string {
	var statements []string
	var current strings.Builder
	inQuote := false

	for i := 0; i < len(content); i++ {
		ch := content[i]
		switch {
		case ch == '\'' && (i == 0 || content[i-1] != '\\'):
			inQuote = !inQuote
			current.WriteByte(ch)
		case ch == ';' && !inQuote:
			statements = append(statements, current.String())
			current.Reset()
		default:
			current.WriteByte(ch)
		}
	}
	if current.Len() > 0 {
		statements = append(statements, current.String())
	}
	return statements
}

func formatValue(v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case bool:
		if val {
			return "TRUE"
		}
		return "FALSE"
	case time.Time:
		return fmt.Sprintf("'%s'", val.Format("2006-01-02 15:04:05.999999"))
	case []byte:
		return escapeString(string(val))
	case string:
		return escapeString(val)
	default:
		return fmt.Sprintf("%v", val)
	}
}

func escapeString(s string) string {
	s = strings.ReplaceAll(s, "'", "''")
	return fmt.Sprintf("'%s'", s)
}

func truncate(s string, max int) string {
	if len(s) > max {
		return s[:max] + "..."
	}
	return s
}
